id: A5F92325C
title: 'Moonlight of Pacifying Amṛta: A Daily Visualization and Recitation for the
  Dispeller of All Samaya Corruptions and Pollutions'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:37:06.912835
  last_modified_at: 2022-03-01 01:37:06.912842
